### ISSUE TITLE
SIGHUP handling is flawed

### ISSUE THREAD

**Issue by equinox0815** [fiorix/go-daemon#14]
Hi,

It's been quite a while since i had to work with signal handling in C but i'm pretty sure the current handling of SIGHUP has a number of issues:

- For one there is a very limited number of functions that are allowed to be called inside of a signal handler and i'm afraid none of the functions called [here](https://github.com/fiorix/go-daemon/blob/b37d4c40e860d1911469c06a74e66fbaafeb0bfe/god.c#L293) are on the list of safe functions: https://www.man7.org/linux/man-pages/man7/signal-safety.7.html
 
- The next issue is that the logger thread does not block the HUP signal ([`pthread_sigmask`](https://man7.org/linux/man-pages/man3/pthread_sigmask.3.html)). This means that it is possible that an incoming SIGHUP might be processed (asynchronously!) by the logger thread. If this happens while it is currently running inside the protected regions [here](https://github.com/fiorix/go-daemon/blob/b37d4c40e860d1911469c06a74e66fbaafeb0bfe/god.c#L276) or [here](https://github.com/fiorix/go-daemon/blob/b37d4c40e860d1911469c06a74e66fbaafeb0bfe/god.c#L283) the call to `pthread_mutex_lock` inside of the sighup handler will lead to a deadlock because the thread is trying to acquire the very same lock it already holds.
 
- The logger thread does not handle short writes to the log file (in fact the current code totally ignores the return value of the `fwrite` function). Actually ignoring return values is kind of happening a lot in the current code... but let's deal with one problem at a time.

Imho there are 2 possible ways to fix those problems:

1. Block SIGHUP for the main thread (before the first call to `phtread_create`) using `pthread_sigmask`. Every child thread will inherit this signal mask ensuring that no thread will ever asynchronously deal with that signal. Then spawn a second thread that uses `sigwait` to synchronously wait for SIGHUP and the do the file re-open stuff currently done inside the sighup handler.

2. Again block the SIGHUP for the main thread and inside the logger thread use `pselect` to simultaneously wait for the signal as well as the `logfd` pipe to become read-able. In fact this should also include the file descriptor to the logfile and wait for it to become writeable in order to properly handle short writes. This solution does not need any mutex because everything logfile related is done inside the same thread.

Afaik solution 1. is the most portable solution but i think having 3 threads for this little bit of functionality is a bit overengineered. Solution 2. is imho much cleaner and easier to understand since there is no need for any mutex. Alas i'm not sure if `pselect` is available on as many systems. Back when i had to deal with this stuff `pselect` was still quite new and not as well supported. This might have changed quite a bit of course..

regards
   christian
   
 P.S.: If preferred i should be able to find some time this weekend to prepare a PR.

**Comment by fiorix** [comment]
Hey this is on point, thank you for taking the time to review the code and submit fixes.
