### ISSUE TITLE
Support reloading of go binary

### ISSUE THREAD

**Issue by difro** [fiorix/go-daemon#2]
It'd be very useful if go-daemon supported re-loading of go binary to ease updating.

Currently, only way to update the currently running go binary is.
- overwrite the old go binary with the updated one.
- kill go-daemon
- re-launch go-daemon with new binary.

Proposed solution:
- go-daemon receives SIGUSR[12] or SIGWINCH.
- go-daemon kills current child(who's exec()-ing old go binary)
- go-daemon re-loads updated go binary and re-exec().

**Comment by fiorix** [comment]
Not doing this for now.
