### ISSUE TITLE
Security: Missing call to initgroups/setgroups

### ISSUE THREAD

**Issue by driskell** [fiorix/go-daemon#4]
I notice when dropping privileges, supplementary groups are not dropped:
https://github.com/fiorix/go-daemon/blob/master/god.c#L160

I've not been able to confirm but this would mean the process retain supplementary groups such as "wheel", and "admin". Only the primary group is dropped. This would allow the process continued access to /var/log and other potentially sensitive areas.

A call to `initgroups(user_pwd, getegid())` should be made after `setegid()` to replace supplementary groups with the specified primary group and the supplementary of the specified user. Alternatively, `setgroups(NULL, 0)` will wipe the supplementary list but usually it's desirable to maintain supplementary groups of the requested user.

**Comment by fiorix** [comment]
That'd be definitely a good addition. Send the patch if you can and I'll merge in.
