### ISSUE TITLE
Daemon stops running when started in a ssh pseudo-terminal

### ISSUE THREAD

**Issue by lancerushing** [fiorix/go-daemon#5]
If I ssh into a server and start a daemon everything works fine.
  1. ssh in.
  2. run daemon
    - $ sudo god -r / -n -l /tmp/test.log -p /tmp/test.pid -- sleep 100
  3. logout 
  4. check if process is still running ... success.

However if I use a pseudo terminal with SSH the process fails:
  1. ssh command:
    - $ ssh -t user@myhost  "sudo god -r / -n -l /tmp/test.log -p /tmp/test.pid -- sleep 100"
  2. check if process is still running ... fail

**Comment by ranrub** [comment]
+1 This happens to me in ubuntu 14.04

**Comment by ranrub** [comment]
The effect I'm seeing is strangely probabilistic - when you start the daemon in pesudotty, about 90% of the times the daemon doesn't start (fails silently). In the other 10% daemon starts and runs normally.
