### ISSUE TITLE
Privilege escalation due to weak privdrop

### ISSUE THREAD

**Issue by threez** [fiorix/go-daemon#6]
this issue is related to #4 but focuses more on the privdrop. In order to make a correct privdrop you need to set more then the effective uid/gid. Using **setresuid** and **setresgid**. 

**From the research:**
There is a pretty good paper regarding this: http://www.cs.berkeley.edu/~daw/papers/setuid-usenix02.pdf

They did a reference implementation:
> The implementation uses setresuid
if available since it has the clearest semantics and
it is able to set each of the user IDs independently

**From The Man Page:**
> Setting the effective user (group) ID to the saved set-user-ID (saved
set-group-ID) is possible since Linux 1.1.37 (1.1.38).  On an
arbitrary system one should check _POSIX_SAVED_IDS.
Under glibc 2.0 seteuid(euid) is equivalent to setreuid(-1, euid) and
hence may change the saved set-user-ID. Under glibc 2.1 and later it
is equivalent to setresuid(-1, euid, -1) and hence does not change
the saved set-user-ID. Analogous remarks hold for setegid(), with
the difference that the change in implementation from setregid(-1,
egid) to setresgid(-1, egid, -1) occurred in glibc 2.2 or 2.3
(depending on the hardware architecture).
According to POSIX.1, seteuid() (setegid()) need not permit euid
(egid) to be the same value as the current effective user (group) ID,
and some implementations do not permit this.

**Important section:**
**_Under glibc 2.1 and later it is equivalent to setresuid(-1, euid, -1) and hence does not change the saved set-user-ID._**

**Comment by fiorix** [comment]
PR?
